### ISSUE TITLE
[Bug] Dynamic Routing in React when using esbuild

### ISSUE THREAD

**Issue by dj0024javia** [simonboisset/create-esbuild#3]
Great Article @simonboisset! I must say I haven't found any article with a detailed explanation of esbuild with react.

I did check all of your examples are those were super helpful. However, I did find a bug where in the case of dynamic routing in react, which is mainly handled by react-router, it navigates properly if you go from / route to /home.

The issue arises when you try to refresh on /home(F5), as it will throw a 404 not found error.
for dev.js -> Change this line
`const path = url.split('/').pop().indexOf('.') ? url :/index.html;`

into the following snippet and it will work just fine for dynamic routing in react with esbuild.

`const path = url.split('/').pop().indexOf('.') > -1 ? url :/index.html;`

Unfortunately, I can't submit PR as I don't have permission!

Cheers

**Comment by dj0024javia** [comment]
PR Link - https://github.com/simonboisset/templates/pull/4

**Comment by simonboisset** [comment]
Hello @dj0024javia . Thanks you for your feedback. I will check your PR soon :)
